- app/models/order.rb
- app/models/order_detail.rb
- db/migrate/20221123005803_create_order_details.rb
- db/schema.rb
- db/seeds.rb
- test/models/order_detail_test.rb
- Added order-details join table, and model
- added validations and associations
> added order details model

- app/controllers/orders_controller.rb
- app/models/delivery_address.rb
- app/models/user.rb
- app/views/layouts/application.html.erb
- app/views/orders/new.html.erb
- db/migrate/20221123050607_create_delivery_addresses.rb
- db/migrate/20221123052729_add_delivery_date_and_comments_columns.rb
- db/schema.rb
- test/models/delivery_address_test.rb
- added bootstrap & popper cdn into app.html 
- WIP on simple form for new order method
- create delivery address model
- added validations & associations
- added delivery_date and comments columns to orders model
> added delivery address table

- app/controllers/products_controller.rb
- app/controllers/suppliers_controller.rb
- app/views/suppliers/index.html.erb
- app/views/suppliers/new.html.erb
- app/views/suppliers/show.html.erb
- config/routes.rb
- test/controllers/products_controller_test.rb
Can now view all suppliers, individual suppliers and create and view new suppliers.
No css done.
> Creating suppliers

- Gemfile.lock
- app/controllers/orders_controller.rb
- app/views/orders/index.html.erb
- app/views/orders/show.html.erb
- config/routes.rb
- Added a route for order index and show as an independent resource 
- Added index and show, and basic html for order's index and show 
- [ x] local server
> order changes

- Gemfile
- Gemfile.lock
- db/schema.rb
- db/seeds.rb
I have created seeds for User, Products, Suppliers
- [ X] New feature (non-breaking change which adds functionality)
- [X ] rails console
> Created seeds for User Product Suppliers

- app/assets/stylesheets/components/_accordion.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_orders.scss
- app/controllers/orders_controller.rb
- app/views/orders/index.html.erb
- app/views/orders/show.html.erb
- db/schema.rb
- Finished Bootstrap Accordion for order's Index page (http://localhost:3000/orders)
- Created order's show page but still a place holder (http://localhost:3000/orders/1)
- [] local server
> Updating order index show

- app/assets/stylesheets/pages/_suppliers.scss
- app/views/suppliers/index.html.erb
- db/schema.rb
Added button style effect to suppliers
> added click button styling to suppliers

- app/models/order.rb
- db/seeds.rb
Currently no seed file for order and order details
I have also started making changes to be able to see a list of templates for a supplier, which I will complete in the next pull request. 
- [ X] local server
> Added order and order details seed file

- app/assets/stylesheets/pages/_suppliers.scss
> added cartoon styling to cards

- app/assets/stylesheets/components/_button.scss
- app/controllers/orders_controller.rb
- app/javascript/controllers/order_status_controller.js
- app/views/orders/index.html.erb
- app/views/orders/show.html.erb
- config/routes.rb
Added a function to mark an order as delivered with a button (submit form) 
> adding mark as delivered

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/pages/_orders.scss
- app/javascript/controllers/order_form_controller.js
- app/views/layouts/application.html.erb
- app/views/orders/_order_details.html.erb
- app/views/orders/new.html.erb
Styling of the orders form:
- added calendar feature
- stylized buttons - if happy this this style of button we can make it a partial and just roll it out through the app
> Order form 2.0

- app/javascript/controllers/index.js
- app/javascript/controllers/order_detail_controller.js
- app/javascript/controllers/order_form_controller.js
- app/views/orders/_order_details.html.erb
- app/views/orders/new.html.erb
- package.json
- yarn.lock
- added order-detail-row stimulus controller for partial
- added js functions to display product price and subtotal
- added js function to display grand total
- moved add row link into nested form container to fix add new rows link
- removed unwanted dependancies - yarn remove cocoon
*remember to yarn install!*
> Feature add create order

- Gemfile.lock
- app/controllers/orders_controller.rb
- app/javascript/controllers/order_status_controller.js
- app/views/layouts/application.html.erb
- app/views/orders/index.html.erb
- app/views/orders/show.html.erb
- db/seeds.rb
- package.json
- yarn.lock
Changed alert message and fixed seed file
> Show turbo and seed file

- Gemfile.lock
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar2.scss
- app/javascript/controllers/index.js
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
- app/views/shared/_navbar2.html.erb
Created side menu navbar with styling
Items in the menu will need to be linked up when ready
> added side nav bar with styling

- app/javascript/controllers/index.js
Please include a summary of the change and/or which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> Removes nabar-2 stimulus controller

- app/views/orders/show.html.erb
- db/seeds.rb
Fixed db.seed to create multiple order details for order 
Created a link to contact suppplier
- [ x] Bug fix (non-breaking change which fixes an issue)
> fixing seed and contact link

- app/views/orders/new.html.erb
- Removed duplicate lines from previous merge
> removed duplicate lines from merge

- db/seeds.rb
Discussed with Rich (will help refactor this on Monday) - but essentially we didnt code the seed file properly..
> Support rolling product ids in seeds

- db/seeds.rb
product: Product.find(Product.all.pluck(:id).sample)
> Product.find changed

- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_push-btn.scss
- app/assets/stylesheets/pages/_orders.scss
- app/views/orders/index.html.erb
- app/views/orders/new.html.erb
- app/views/shared/_navbar2.html.erb
- app/views/suppliers/show.html.erb
- created component for "button" with a push down effect
- linked up navbar - fully functional now
> Refactoring css components

- app/assets/stylesheets/components/_alert.scss
- app/assets/stylesheets/pages/_orders.scss
- app/controllers/orders_controller.rb
- app/views/layouts/application.html.erb
- app/views/orders/_order_mark_delivered.html.erb
- app/views/orders/_order_show.html.erb
- app/views/orders/_order_template_details.html.erb
- app/views/orders/show.html.erb
- app/views/pages/home.html.erb
- Added a logic show "mark as delivered" btn only for orders whose status is not "delivered"
- Added a total amount column for order (orders/:id)
- Moved alert box to the top 
- Created two partial html files for cleaner show.html.erb 
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [] rails console
> Order's show page changes 

- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_orders.scss
- app/views/layouts/application.html.erb
- app/views/orders/_order_show.html.erb
- app/views/orders/index.html.erb
- app/views/orders/show.html.erb
- Just front end changes for order's index and show pages (confirmed no conflicts with the previous master) 
- Changed the default font back from Inter as Inter doesn't have bold font (_fonts.scss)
> front end fixes

- app/models/order.rb
- app/models/order_detail.rb
- app/models/template.rb
- db/migrate/20221125121800_create_templates.rb
- db/migrate/20221126063551_create_order_type_column.rb
- db/migrate/20221127032311_make_order_details_polymorphic.rb
- db/schema.rb
- db/seeds.rb
- test/models/template_test.rb
- added template model with valids and assocs
- changed order_details to polymorphic associations to Order and Template Models as: :order
- edited seed file
- updated order model assocs
> Feature add templates model

- app/assets/stylesheets/pages/_suppliers.scss
- app/controllers/suppliers_controller.rb
- app/views/layouts/application.html.erb
- app/views/suppliers/show.html.erb
> Styling suppliers

- app/assets/stylesheets/pages/_orders.scss
- app/assets/stylesheets/pages/_suppliers.scss
- app/controllers/suppliers_controller.rb
- app/views/layouts/application.html.erb
- app/views/orders/_orders_index.html.erb
- app/views/orders/_templates_index.html.erb
- app/views/orders/index.html.erb
- app/views/suppliers/show.html.erb
Display fixed on phone conversion
> Bug on display

- app/assets/stylesheets/pages/_suppliers.scss
- app/models/supplier.rb
- app/views/shared/_navbar2.html.erb
- app/views/suppliers/show.html.erb
fixed user flows on suppliers:
- added templates button on suppliers tab to take to right page
> Userflow bugs

- app/views/orders/_order_mark_delivered.html.erb
- app/views/suppliers/show.html.erb
Fixed btns for supplier and order show pages 
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] local server
> fixing btns

- app/assets/stylesheets/pages/_suppliers.scss
small change - removed highlights
> highlights removed

- app/controllers/inventories_controller.rb
- app/models/inventory.rb
- app/models/product.rb
- app/models/user.rb
- config/routes.rb
- db/migrate/20221129025941_create_inventories.rb
- db/migrate/20221129034849_change_user_id_not_null_inventories.rb
- db/migrate/20221129035919_change_user_id_not_nul_not_rolled_back_inventories.rb
- db/migrate/20221129041530_change_column_inventories.rb
- db/migrate/20221129042041_change_column_reference_inventories.rb
- db/schema.rb
- test/controllers/inventories_controller_test.rb
- test/models/inventory_test.rb
Description
We are adding inventory capability into the app.
Through this pull request, I have added:
- inventory model
- inventories controller
> Created inventory controller and model

- db/seeds.rb
I have generated inventory balances in the seed file.
> Updated seed file for inventory starting balance

- app/assets/stylesheets/components/_navbar2.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_results.scss
- app/views/pages/results.html.erb
- app/views/shared/_searchbar.html.erb
- db/schema.rb
> Restyling search

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_searchbar2.scss
- app/assets/stylesheets/components/_searchbar3.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_products.scss
- app/controllers/products_controller.rb
- app/views/products/index.html.erb
- app/views/products/show.html.erb
- app/views/shared/_navbar2.html.erb
- app/views/shared/_searchbar2.html.erb
- app/views/shared/_searchbar3.html.erb
- config/routes.rb
- db/schema.rb
Please include a summary of the change and/or which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> Dynamic search

- app/controllers/products_controller.rb
- app/views/products/show.html.erb
Small fix to link products and inventory + styling fixed for products page
> Bug fix: Inventories x Products

- app/assets/stylesheets/components/_navbar2.scss
- app/assets/stylesheets/config/_fonts.scss
- app/views/layouts/application.html.erb
- db/schema.rb
- fixed syntax error in scss file that causes page to fail 
- moved import tag to scss config that causes page to fail
> fixed syntax and moved material font imports from app.html to scss config

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/views/pages/_landing_page.html.erb
- app/views/shared/_navbar2.html.erb
- created feature cards with images
- added footer(social icons, links, and logo)
> Wip css rework homepage 02

- config/environments/production.rb
- Added configs for production.rb for use in heroku 
> added action mailer config for production

- app/assets/stylesheets/pages/_home.scss
- app/controllers/inventories_controller.rb
- app/services/update_inventory_service.rb
- app/views/devise/sessions/new.html.erb
- app/views/shared/_navbar2.html.erb
Refactored Inventory Controller into service file as per discussion with Rich.
** Please pull the branch down and test it locally on yours too before merging **
Have not broken down the method in the service file any further - can do this later w/ discussion.
> Refactoring inventory controller

- app/controllers/orders_controller.rb
- config/routes.rb
This refactoring
- adds strong params in the order controller
- remove the bang after save!, which means that an error message is displayed when a new order is created without a delivery address (previously no error message was displayed on the screen, only in the logs)
> Order controller refactoring

- app/assets/stylesheets/pages/_suppliers.scss
- app/views/suppliers/show.html.erb
> formatted suppliers/:id page

- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_suppliers.scss
- app/assets/stylesheets/pages/_templates.scss
- app/views/inventories/_inventory_accordion.html.erb
- app/views/orders/_new_order.html.erb
- app/views/orders/_order_accordion.html.erb
- app/views/orders/_template_accordion.html.erb
- app/views/orders/_templates_index.html.erb
Updated template and order pages
- [ x] local server
> Template and order page changes

- app/javascript/controllers/order_detail_controller.js
- app/views/orders/_order_details.html.erb
- app/views/orders/_template_details.erb
Fixed stimulus logic for order details
> Fixed stimulus logic

- app/assets/stylesheets/components/_form.scss
- app/models/order.rb
- db/seeds.rb
- lib/seeds/product_seeds.csv
Updated seed file in preparation for pitch
- lesser order seeds
- lesser template seeds
- more realistic products and price points
> Updated seed file

- app/assets/stylesheets/components/_form.scss
- app/views/orders/_new_order.html.erb
- app/views/orders/_new_order_with_template.html.erb
- app/views/orders/_order_details.html.erb
- app/views/orders/_template_details.erb
- config/locales/simple_form.en.yml
- Form front end changes for two scenarios - creating a new order with new template, or with an existing template (**editing template** is not included) 
http://localhost:3000/orders/new?template=1
- [ x] local server
> Front end dashboard

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_status-badges.scss
- app/assets/stylesheets/pages/_orders.scss
- app/assets/stylesheets/pages/_suppliers.scss
- app/views/inventories/_inventories_counted_dropdown.html.erb
- app/views/inventories/index.html.erb
- app/views/orders/_order_photo_show_edit.html.erb
- app/views/orders/_order_show.html.erb
- app/views/orders/show.html.erb
- app/views/suppliers/show.html.erb
Front end changes as per the attached images 
- Created new btn style (.btn-action / .btn-action:hover / .btn-action-link / .btn-action-link:hover) in _button.scss 
- Changed sync with POS data to icon on inventory index page 
- [ x] New feature (non-breaking change which adds functionality)
- [x ] local server
> Order show/ supplier show / inventory index page front end 

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/pages/_inventories.scss
- app/controllers/orders_controller.rb
- app/views/inventories/_inventory_accordion.html.erb
- app/views/inventories/index.html.erb
- app/views/orders/_order_status_dropdown.html.erb
- app/views/orders/_order_status_dropdown_supplier.html.erb
- app/views/orders/_template_accordion.html.erb
- app/views/products/show.html.erb
- db/seeds.rb
- Product show page 
- Minor changes to inventory index page
- Minor update to seed file to remove lemon and soymilk as they are no longer needed 
- [x ] local server
> Front end changes for product show and inventory page

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar2.scss
- app/assets/stylesheets/components/_notif-cards.scss
- app/assets/stylesheets/components/_tabs.scss
- app/models/inventory.rb
- app/views/orders/_new_order.html.erb
- app/views/pages/_orders_list.html.erb
- app/views/pages/_products_list.html.erb
- app/views/pages/_templates_list.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar2.html.erb
- db/seeds.rb
- added tabs to dashboard
- fixed seed position in supplier create
- added low products in dashboard tab
- stylised tabs contents with tray links
- added quick links and greeter message
- added styling for logout button
> Wip css rework dashboard
